# Generated by Django 4.2.1 on 2024-04-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=1, upload_to='recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
