# Generated by Django 4.2.1 on 2024-04-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0002_recipe_image_recipe_recipe_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
